services:
  postgres:
    image: postgres:16
    container_name: yieldfi_backend
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yieldfi_db
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    networks:
      - prisma_network
    command: 
      - "postgres"
      - "-c"
      - "log_statement=all"  

volumes:
  postgres_data:      

networks:
  prisma_network:  